#version 450

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (set = 0, binding = 0, rgba8) uniform image2D img;






//----------------------------------------------
#define grain
#define vignette
//#define pseudoVintage
#define vignetteColor vec3(0.5)
#define vignetteBlur 0.1
#define vignetteRadius 0.09


float noise(vec2 p) {
    return fract(sin(dot(p, vec2(1.0, 113.0))) * 43758.5453123);
}

vec2 curve(vec2 uv)
{
    uv = (uv - 0.5) * 2.0;
    uv *= 1.1;
    uv.x *= 1.0 + pow((abs(uv.y) / 5.0), 2.0);
    uv.y *= 1.0 + pow((abs(uv.x) / 4.0), 2.0);
    uv = (uv / 2.0) + 0.5;
    uv = uv * 0.92 + 0.04;
    return uv;
}


void CRT(in vec2 uv0, inout vec4 FragColor) {
        
    vec2 uv = curve(uv0);
    float left = 0.0;
    float right = 1.0;
    float up = 1.0;
    float down = 0.0;
    vec2 blur = vec2(0.001, 0.001);

    vec3 col = vec3(smoothstep(left, left + blur.x, uv.x));
    col *= vec3(1.0 - smoothstep(right - blur.x, right, uv.x));
    col *= vec3(smoothstep(down, down + blur.y, uv.y));
    col *= vec3(1.0 - smoothstep(up - blur.y, up, uv.y));
    col = (1.0 - col);


    if (uv.x > left && uv.x < right && uv.y <up && uv.y > down) {
        vec2 center = vec2((left + right) * 0.5, (up + down) * 0.5);
        col = FragColor.xyz;

#ifdef vignette
        float m = pow(pow(uv.x - center.x, 2.0) + pow(uv.y - center.y, 2.0), 0.5);
        float d = distance(vec2(left, up), vec2(center.x, center.y)) - vignetteRadius;
        col *= (1.0 - smoothstep(d - vignetteBlur, d, m) * vignetteColor);
#endif

#ifdef grain 
        col = mix(col, vec3(noise(uv)), 0.1);
#endif
#ifdef pseudoVintage
        col = mix(col, FragColor.xyz, 0.15);
#endif


    }
    else col = vec3(uv.x * uv.y + 0.7);

    if (uv.x > 1.0 || uv.x < 0.0 || uv.y > 1.0 || uv.y < 0.0)
        col = vec3(0.0, 0.0, 0.0);

    FragColor = vec4(col, 1.0);
}

//---------------------------------------------------



void main() 
{
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    vec4 pixel = vec4(0.0,0.0,0.0, 1.0);
    
    vec2 uv = vec2(coord) / vec2(500.0, 500.0);
    vec4 r  = vec4(imageLoad(img, coord));

    CRT(uv,r);

    imageStore(img, coord, vec4( pow(r.x, 1.0 / 2.2), pow(r.y, 1.0 / 2.2) , pow(r.z, 1.0 / 2.2) , 1.0) );
}
